name: osticket-triage

services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  osticket:
    build: 
     context: ..
     dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  splunk:
    image: splunk/splunk:latest
    restart: always
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
    ports:
      - "8010:8000"
      - "8088:8088"
    volumes:
      - splunk_data:/opt/splunk/var
volumes:
  db_data:
  splunk_data:
