name: osticket-triage

services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  osticket:
    build: 
     context: ..
     dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./ost-config.php:/var/www/html/include/ost-config.php
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  splunk:
    image: splunk/splunk:latest
    restart: always
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
    ports:
      - "127.0.0.1:8010:8000"
      - "127.0.0.1:8088:8088"
      - "127.0.0.1:8089:8089"
    volumes:
      - splunk_data:/opt/splunk/var
      - ./splunk-apps/botsv3_data_set:/opt/splunk/etc/apps/botsv3_data_set
      - ./splunk-provisioning/triage_agent_role:/opt/splunk/etc/apps/triage_agent_role
      - ./splunk-provisioning/custom_tls:/opt/splunk/etc/apps/custom_tls
volumes:
  db_data:
  splunk_data:
