#!/usr/bin/env bash
# Writes the recipient for the Splunk alerts that watch the triage agent.
#
# The searches, their schedules and their wording all ship in
# splunk-provisioning/triage_alerts/default/savedsearches.conf. The one value
# that cannot is who the mail goes to, so it is read from docker/.env and
# written into the app's local/ directory, which Splunk merges over default/
# and which this repo does not track.
#
# Splunk's own SMTP credentials are not set here. They are Splunk-wide settings
# under Settings, Server settings, Email settings, and a password does not
# belong in a repo or in a script's arguments.
#
# Safe to re-run. It rewrites the file from scratch each time.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
LOCAL_DIR="$SCRIPT_DIR/splunk-provisioning/triage_alerts/local"
DEFAULT_CONF="$SCRIPT_DIR/splunk-provisioning/triage_alerts/default/savedsearches.conf"

if [ ! -f "$ENV_FILE" ]; then
  echo "docker/.env not found. Copy .env.example to .env and fill in real values first." >&2
  exit 1
fi

SPLUNK_ALERT_EMAIL=$(grep -m1 '^SPLUNK_ALERT_EMAIL=' "$ENV_FILE" | cut -d= -f2-)
SPLUNK_PASSWORD=$(grep -m1 '^SPLUNK_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)
: "${SPLUNK_ALERT_EMAIL:?SPLUNK_ALERT_EMAIL must be set in docker/.env}"
: "${SPLUNK_PASSWORD:?SPLUNK_PASSWORD must be set in docker/.env}"

SPLUNK_CONTAINER="${SPLUNK_CONTAINER:-osticket-triage-splunk-1}"
SPLUNK_REST_HOST="${SPLUNK_REST_HOST:-localhost}"
SPLUNK_REST_PORT="${SPLUNK_REST_PORT:-8089}"
CACERT="$SCRIPT_DIR/splunk-provisioning/custom_tls/default/certs/cacert.pem"
APP_DIR="/opt/splunk/etc/apps/triage_alerts"

# The stanza names come from default/, so adding an alert there needs no change
# here and the two cannot drift apart.
mapfile -t ALERTS < <(grep -oP '^\[\K[^]]+' "$DEFAULT_CONF")
if [ "${#ALERTS[@]}" -eq 0 ]; then
  echo "No alerts found in $DEFAULT_CONF" >&2
  exit 1
fi

mkdir -p "$LOCAL_DIR"
{
  echo "# Generated by provision-splunk-alerts.sh from docker/.env."
  echo "# Edit SPLUNK_ALERT_EMAIL there and re-run, rather than editing this file."
  echo
  for alert in "${ALERTS[@]}"; do
    echo "[$alert]"
    echo "action.email.to = $SPLUNK_ALERT_EMAIL"
    echo
  done
} > "$LOCAL_DIR/savedsearches.conf"

echo "Wrote ${#ALERTS[@]} alert recipient(s) to $LOCAL_DIR/savedsearches.conf"
printf '  %s\n' "${ALERTS[@]}"

# Loading it is part of the job. Leaving the file on disk and printing the
# commands would mean the recipient looks set while Splunk still holds the
# placeholder, and the reload needs the admin password, which does not belong
# on screen.
if ! docker inspect "$SPLUNK_CONTAINER" >/dev/null 2>&1; then
  echo
  echo "Container '$SPLUNK_CONTAINER' is not running, so nothing was loaded."
  echo "Start the stack and re-run this, or set SPLUNK_CONTAINER if it is named differently."
  exit 0
fi

docker exec -u root "$SPLUNK_CONTAINER" mkdir -p "$APP_DIR/local"
docker cp "$LOCAL_DIR/savedsearches.conf" "$SPLUNK_CONTAINER:$APP_DIR/local/savedsearches.conf"
docker exec -u root "$SPLUNK_CONTAINER" chown -R splunk:splunk "$APP_DIR"

http_code=$(curl -s --cacert "$CACERT" -o /dev/null -w '%{http_code}' \
  -u "admin:${SPLUNK_PASSWORD}" -X POST \
  "https://${SPLUNK_REST_HOST}:${SPLUNK_REST_PORT}/services/apps/local/triage_alerts/_reload")

if [[ "$http_code" == 2* ]]; then
  echo "Loaded into Splunk."
else
  echo "Copied, but Splunk did not reload (HTTP $http_code). Restart Splunk to pick it up." >&2
  exit 1
fi
