import os
import time
import requests
from datetime import datetime, timezone

SPLUNK_HEC_URL = os.getenv("SPLUNK_HEC_URL")
SPLUNK_HEC_TOKEN = os.getenv("SPLUNK_HEC_TOKEN")
if not SPLUNK_HEC_URL or not SPLUNK_HEC_TOKEN:
    raise RuntimeError("SPLUNK_HEC_URL and SPLUNK_HEC_TOKEN must both be set")

# CA cert generated by docker/generate-splunk-cert.sh, unique to this
# deployment.
SPLUNK_CACERT_PATH = os.path.join(
    os.path.dirname(__file__), "..", "docker", "splunk-provisioning",
    "custom_tls", "default", "certs", "cacert.pem"
)

def _send_audit_event(event_content):
    payload = {
        "time": datetime.now(timezone.utc).timestamp(),
        "sourcetype": "osticket:triage:audit",
        "index": "osticket_triage",
        "event": event_content,
    }
    headers = {"Authorization": f"Splunk {SPLUNK_HEC_TOKEN}"}
    last_error = None
    for attempt in range(3):
        try:
            response = requests.post(
                SPLUNK_HEC_URL, headers=headers, json=payload, verify=SPLUNK_CACERT_PATH, timeout=5
            )
            # A 4xx means Splunk understood the request and refused it: bad
            # token, unknown index, malformed event. Retrying cannot change
            # that, so it fails immediately rather than burning three attempts.
            if 400 <= response.status_code < 500:
                print(f"Splunk rejected the audit event: {response.status_code} {response.text[:200]}")
                return False
            response.raise_for_status()
            return True
        except requests.exceptions.RequestException as e:
            last_error = e
            if attempt < 2:
                time.sleep([1, 3][attempt])
    print(f"Splunk logging failed after 3 attempts: {last_error}")
    return False

# ticket_id is passed only where the HMAC signature already verified. On a
# signature failure the body is unverified, so nothing from it is recorded.
def log_request_rejected(reason, source_ip, ticket_id=None):
    return _send_audit_event({
        "ticket_id": ticket_id,
        "status": "request_rejected",
        "reason": reason,
        "source_ip": source_ip,
    })

def log_classification(ticket_id, subject, classification, requester_verified):
    return _send_audit_event({
        "ticket_id": ticket_id,
        "status": "classification_complete",
        "subject": subject,
        "category": classification.category.value,
        "severity": classification.severity.value,
        "confidence": classification.confidence.value,
        # Whether osTicket authenticated the submitter as the requester address.
        # False means the email was never eligible as a search target.
        "requester_verified": requester_verified,
        # Informational only. Extracted from ticket text and validated, but
        # never used to build a query. See build_enrichment_query for why.
        "extracted_hostname": classification.hostname,
        "extracted_username": classification.username,
        "extracted_source_ip": classification.source_ip,
    })

def log_classification_failure(ticket_id, failure_type, error):
    return _send_audit_event({
        "ticket_id": ticket_id,
        "status": "classification_failed",
        "failure_type": failure_type,
        "error": error,
    })

def log_enrichment(ticket_id, events):
    return _send_audit_event({
        "ticket_id": ticket_id,
        "status": "enrichment_complete",
        "event_count": len(events),
        "events": events,
    })

def log_enrichment_skipped(ticket_id, reason):
    return _send_audit_event({
        "ticket_id": ticket_id,
        "status": "enrichment_skipped",
        "reason": reason,
    })

def log_enrichment_failure(ticket_id, failure_type, error):
    return _send_audit_event({
        "ticket_id": ticket_id,
        "status": "enrichment_failed",
        "failure_type": failure_type,
        "error": error,
    })
